[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
rayon = "1.8"

bluer = { version = "0.16.1", features = ["rfcomm", "bluetoothd", "full"], default-features = false }
 #features = ["bluetoothd"], default-features = false }
tokio = { version = "1.35.1", features =["rt-multi-thread"]}
futures = "0.3"

[lib]

[[bin]]
name = "main"

[[bin]]
name = "test-bl"

[build-dependencies]
bindgen = "0.69"
